version: '2'
MAINTAINER SATHYA CHILUMULA
 services:
    db:
       image: mysql:5.7
       restart: always
       volumes:
          -db_data:/var/lib/mysql
       environment:
          MYSQL_ROOT_PASSWORD: p4ssw@rd!
       networks:
          - back
 networks:
    back:
 volumes:
    db_data:
